allFiles:
	gcc ../src/hmi.c -o hmi
	gcc ../src/ecu.c ../lib/socketManager.c ../lib/fileManager.c -o ecu
	gcc ../src/frontWindshieldCamera.c ../lib/socketManager.c ../lib/fileManager.c -o fwc
	gcc ../src/blindSpot.c ../lib/socketManager.c ../lib/fileManager.c -o bs
	gcc ../src/parkAssist.c ../lib/socketManager.c ../lib/fileManager.c -o pa
	gcc ../src/surroundViewCameras.c ../lib/socketManager.c ../lib/fileManager.c -o svc
	gcc ../src/steerByWire.c ../lib/socketManager.c ../lib/fileManager.c -o sbw
	gcc ../src/brakeByWire.c ../lib/socketManager.c ../lib/fileManager.c -o bbw
	gcc ../src/throttleControl.c ../lib/socketManager.c ../lib/fileManager.c -o tc
	gcc ../src/forwardFacingRadar.c ../lib/socketManager.c ../lib/fileManager.c -o ffr
	
